import { pathToFileURL } from "node:url";
import { CATALOG_SYSTEMS } from "schemas";
import { logger } from "../config/logger.js";
import { connectDB, disconnectDB, prisma } from "../config/prisma.js";
import { computeProductSearchText } from "../modules/catalog/searchText.js";
import { supplyRouteFromWire, systemCodeFromWire, toColumns } from "../utils/serialize.js";
import { BRAND_SEED_DATA, CATEGORY_TEMPLATES, SUPPLY_ROUTE_ROTATION } from "./catalog.data.js";
import { seedVehicles } from "./vehicles.js";

const VARIANTS_PER_TEMPLATE = 4;

interface FlatModel {
  makeId: string;
  modelId: string;
  modelSlug: string;
  genId: string;
  yearFrom: number;
  yearTo: number | null;
}

/**
 * Every seeded VehicleModel paired with its first generation — the fitment
 * target each generated product/Fitment pair uses. Real vehicles from the
 * actual P2.S6 seed tree, queried at seed time rather than hardcoded, so this
 * never drifts from whatever seedVehicles() produces.
 *
 * One query with the generations included, where Mongo needed a query per
 * model. `take: 1` with the ordering does the "earliest generation" pick in
 * the database rather than in a loop.
 */
async function loadFlatModels(): Promise<FlatModel[]> {
  // The `orderBy` is load-bearing, not tidiness. Products are generated by
  // pairing each template with `flatModels[index % flatModels.length]`, so the
  // slug a template produces depends entirely on this order -- and PostgreSQL
  // does not promise one without `ORDER BY`. It returned a different order on
  // the second run (updated rows move), which paired templates with different
  // vehicles, produced different slugs, and made the "idempotent" seed create
  // a second full catalogue: 320 products became 640. Mongo's natural `_id`
  // order was stable by accident, so nothing here had ever needed to say it.
  const models = await prisma.vehicleModel.findMany({
    orderBy: [{ makeId: "asc" }, { slug: "asc" }],
    include: {
      generations: { where: { deletedAt: null }, orderBy: { yearFrom: "asc" }, take: 1 },
    },
  });
  return models.flatMap((model) => {
    const gen = model.generations[0];
    if (!gen) return [];
    return [
      {
        makeId: model.makeId,
        modelId: model.id,
        modelSlug: model.slug,
        genId: gen.id,
        yearFrom: gen.yearFrom,
        yearTo: gen.yearTo,
      },
    ];
  });
}

function warrantyText(months: number): string {
  return months > 0 ? `${months} ماه ضمانت` : "کالای مصرفی — بدون ضمانت زمانی";
}

/**
 * Idempotent (upsert on Product.slug, then Fitment on its natural key) —
 * >= 300 products across 10 categories/15 brands (P3.S7), generated from
 * CATEGORY_TEMPLATES x compatible vehicle models rather than 300
 * hand-written literals. Depends on the real vehicle tree (P2.S6), so it
 * seeds vehicles first if that hasn't happened yet in this run.
 */
export async function seedCatalog(): Promise<void> {
  await seedVehicles();

  for (const system of CATALOG_SYSTEMS) {
    const fields = {
      ...toColumns(system.name),
      systemCode: systemCodeFromWire(system.code),
      parentId: null,
      path: [],
    };
    await prisma.category.upsert({
      where: { slug: system.slug },
      update: fields,
      create: { ...fields, slug: system.slug },
    });
  }

  for (const brand of BRAND_SEED_DATA) {
    const fields = { ...toColumns(brand.name), country: brand.country, isOEM: brand.isOEM };
    await prisma.brand.upsert({
      where: { slug: brand.slug },
      update: fields,
      create: { ...fields, slug: brand.slug },
    });
  }

  const flatModels = await loadFlatModels();
  if (flatModels.length === 0) {
    throw new Error("seedCatalog: no vehicle models found — seedVehicles() produced nothing");
  }

  // Resolved once instead of per product. The Mongo version re-queried the
  // brand inside the innermost loop -- roughly 300 extra round trips to look
  // up fifteen rows.
  const brandsBySlug = new Map(
    (await prisma.brand.findMany({ select: { id: true, slug: true } })).map((row) => [
      row.slug,
      row.id,
    ]),
  );
  const categoriesBySlug = new Map(
    (await prisma.category.findMany({ select: { id: true, slug: true } })).map((row) => [
      row.slug,
      row.id,
    ]),
  );

  let productCount = 0;
  let fitmentCount = 0;
  let globalIndex = 0;

  for (const group of CATEGORY_TEMPLATES) {
    const categoryId = categoriesBySlug.get(group.categorySlug);
    if (!categoryId) throw new Error(`seedCatalog: category "${group.categorySlug}" not found`);

    for (const template of group.templates) {
      for (let i = 0; i < VARIANTS_PER_TEMPLATE; i += 1) {
        const vehicle = flatModels[(globalIndex * VARIANTS_PER_TEMPLATE + i) % flatModels.length]!;
        const brand = BRAND_SEED_DATA[productCount % BRAND_SEED_DATA.length]!;
        const brandId = brandsBySlug.get(brand.slug)!;
        const supplyRoute = SUPPLY_ROUTE_ROTATION[productCount % SUPPLY_ROUTE_ROTATION.length]!;
        const priceRial =
          template.priceMinRial +
          Math.round(
            ((template.priceMaxRial - template.priceMinRial) * i) / (VARIANTS_PER_TEMPLATE - 1),
          );
        // P6.S1: dev/test data for wholesale pricing -- 15% off retail
        // (a real, defensible trade-discount figure, not an arbitrary
        // number), rounded to the nearest 1,000 Rial the same way an
        // admin would actually round a price.
        const wholesalePriceRial = Math.round((priceRial * 0.85) / 1000) * 1000;
        const slug = `${template.slugBase}-${vehicle.modelSlug}`;
        const sku = `SKU-${group.categorySlug}-${template.slugBase}-${vehicle.modelSlug}`
          .toUpperCase()
          .replace(/[^A-Z0-9]+/g, "-");

        const oemNumbers = [`${template.oemPrefix}-${vehicle.modelSlug.toUpperCase()}`];
        const crossRefNumbers = [`XREF-${sku}`];
        const names = toColumns(template.name);

        const fields = {
          ...names,
          sku,
          oemNumbers,
          crossRefNumbers,
          // Still computed explicitly, and still for the reason the original
          // comment gave: the derive step is not automatic. `searchVector` is
          // a generated column now, but it generates from `searchText`, and
          // `searchText` is this.
          searchText: computeProductSearchText({ ...names, sku, oemNumbers, crossRefNumbers }),
          brandId,
          categoryId,
          media: [],
          priceRial,
          wholesalePriceRial,
          taxRate: 9,
          stock: 5 + (productCount % 20),
          lowStockAt: 5,
          backorderable: false,
          weightGram: template.weightGram,
          lengthMm: template.dimensions.lengthMm,
          widthMm: template.dimensions.widthMm,
          heightMm: template.dimensions.heightMm,
          warrantyMonths: template.warrantyMonths,
          warrantyText: warrantyText(template.warrantyMonths),
          supplyRoute: supplyRouteFromWire(supplyRoute),
          sourceBrand: brand.name.en,
          countryOfManufacture: brand.country,
          verificationCode: `VER-${sku}`,
          status: "active" as const,
        };

        const product = await prisma.product.upsert({
          where: { slug },
          update: fields,
          create: { ...fields, slug },
        });
        productCount += 1;

        // Fitment has no unique constraint on this key on purpose -- a product
        // legitimately has several fitment rows for one model across different
        // year ranges and engines -- so this is find-then-write rather than an
        // upsert. See the note in schema.prisma.
        const fitmentFields = {
          yearFrom: vehicle.yearFrom,
          yearTo: vehicle.yearTo,
          confidence: "exact" as const,
        };
        const key = {
          productId: product.id,
          makeId: vehicle.makeId,
          modelId: vehicle.modelId,
          genId: vehicle.genId,
        };
        const existing = await prisma.fitment.findFirst({ where: key, select: { id: true } });
        if (existing) {
          await prisma.fitment.update({ where: { id: existing.id }, data: fitmentFields });
        } else {
          await prisma.fitment.create({ data: { ...key, ...fitmentFields } });
        }
        fitmentCount += 1;
      }
      globalIndex += 1;
    }
  }

  logger.info(
    {
      products: productCount,
      fitments: fitmentCount,
      categories: CATALOG_SYSTEMS.length,
      brands: BRAND_SEED_DATA.length,
    },
    "Catalog seed complete",
  );
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  connectDB()
    .then(() => seedCatalog())
    .then(() => disconnectDB())
    .catch((err: unknown) => {
      logger.error({ err }, "Catalog seed failed");
      process.exit(1);
    });
}
