export interface BrandSeed {
  name: { fa: string; en: string };
  slug: string;
  country: string;
  isOEM: boolean;
}

// §5's brand wall already names Bosch/Valeo/Mahle/SKF/Denso/NGK/ایساکو/
// سایپا یدک — extended to 15 with other real, globally-recognized
// automotive-parts manufacturers genuinely present in the Iranian
// aftermarket, for P3.S7's ">= 15 brands" requirement. ایساکو and سایپا
// یدک are IKCO's and Saipa's own OEM parts arms respectively.
export const BRAND_SEED_DATA: BrandSeed[] = [
  { name: { fa: "بوش", en: "Bosch" }, slug: "bosch", country: "Germany", isOEM: true },
  { name: { fa: "والئو", en: "Valeo" }, slug: "valeo", country: "France", isOEM: true },
  { name: { fa: "ماله", en: "Mahle" }, slug: "mahle", country: "Germany", isOEM: true },
  { name: { fa: "اس‌کی‌اف", en: "SKF" }, slug: "skf", country: "Sweden", isOEM: true },
  { name: { fa: "دنسو", en: "Denso" }, slug: "denso", country: "Japan", isOEM: true },
  { name: { fa: "ان‌جی‌کی", en: "NGK" }, slug: "ngk", country: "Japan", isOEM: true },
  { name: { fa: "ایساکو", en: "Isaco" }, slug: "isaco", country: "Iran", isOEM: true },
  {
    name: { fa: "سایپا یدک", en: "Saipa Yadak" },
    slug: "saipa-yadak",
    country: "Iran",
    isOEM: true,
  },
  { name: { fa: "دلفی", en: "Delphi" }, slug: "delphi", country: "United Kingdom", isOEM: true },
  {
    name: { fa: "فبی بیلشتاین", en: "Febi Bilstein" },
    slug: "febi-bilstein",
    country: "Germany",
    isOEM: false,
  },
  { name: { fa: "تی‌آردبلیو", en: "TRW" }, slug: "trw", country: "Germany", isOEM: true },
  { name: { fa: "زاکس", en: "Sachs" }, slug: "sachs", country: "Germany", isOEM: true },
  { name: { fa: "گیتس", en: "Gates" }, slug: "gates", country: "United States", isOEM: false },
  {
    name: { fa: "کنتیننتال", en: "Continental" },
    slug: "continental",
    country: "Germany",
    isOEM: true,
  },
  { name: { fa: "برمبو", en: "Brembo" }, slug: "brembo", country: "Italy", isOEM: true },
];

/**
 * Wire spellings, not the generated enum members. A Prisma enum member cannot
 * contain a hyphen, so these are `@map`ped in the schema and converted at the
 * write -- seed/catalog.ts calls `supplyRouteFromWire`. Typing this array as
 * `SupplyRoute` would be the wrong end of that bridge.
 */
export const SUPPLY_ROUTE_ROTATION: string[] = [
  "oem",
  "genuine-imported",
  "domestic",
  "grade1-aftermarket",
];

export interface PartTemplate {
  name: { fa: string; en: string };
  slugBase: string;
  weightGram: number;
  dimensions: { lengthMm: number; widthMm: number; heightMm: number };
  warrantyMonths: number;
  priceMinRial: number;
  priceMaxRial: number;
  oemPrefix: string;
}

export interface CategoryTemplates {
  categorySlug: string;
  templates: PartTemplate[];
}

// Real, distinct Persian part names per §1.3's automotive-system taxonomy
// (packages/schemas/catalogSystems.ts) — not literally sourced OEM part
// numbers/prices (those are invented-but-plausible per P3.S7's own
// "plausible Rial prices" wording), but real part names any Iranian
// mechanic would recognize. Each template generates several SKUs (one per
// compatible vehicle model, see seed/catalog.ts) to reach the >= 300
// product requirement without 300 hand-written literals.
export const CATEGORY_TEMPLATES: CategoryTemplates[] = [
  {
    categorySlug: "engine",
    templates: [
      {
        name: { fa: "واشر سرسیلندر", en: "Cylinder Head Gasket" },
        slugBase: "cylinder-head-gasket",
        weightGram: 250,
        dimensions: { lengthMm: 400, widthMm: 200, heightMm: 5 },
        warrantyMonths: 6,
        priceMinRial: 1_200_000,
        priceMaxRial: 2_500_000,
        oemPrefix: "11141",
      },
      {
        name: { fa: "تسمه تایم", en: "Timing Belt" },
        slugBase: "timing-belt",
        weightGram: 300,
        dimensions: { lengthMm: 900, widthMm: 25, heightMm: 10 },
        warrantyMonths: 12,
        priceMinRial: 900_000,
        priceMaxRial: 1_800_000,
        oemPrefix: "13568",
      },
      {
        name: { fa: "زنجیر تایم", en: "Timing Chain" },
        slugBase: "timing-chain",
        weightGram: 800,
        dimensions: { lengthMm: 500, widthMm: 20, heightMm: 20 },
        warrantyMonths: 12,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_500_000,
        oemPrefix: "13506",
      },
      {
        name: { fa: "رینگ پیستون", en: "Piston Ring Set" },
        slugBase: "piston-ring-set",
        weightGram: 400,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_000_000,
        oemPrefix: "13011",
      },
      {
        name: { fa: "یاتاقان میل‌لنگ", en: "Crankshaft Bearing Set" },
        slugBase: "crankshaft-bearing-set",
        weightGram: 350,
        dimensions: { lengthMm: 150, widthMm: 100, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 1_400_000,
        priceMaxRial: 2_800_000,
        oemPrefix: "11701",
      },
      {
        name: { fa: "سوپاپ دود", en: "Exhaust Valve" },
        slugBase: "exhaust-valve",
        weightGram: 120,
        dimensions: { lengthMm: 100, widthMm: 30, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 600_000,
        priceMaxRial: 1_400_000,
        oemPrefix: "13715",
      },
      {
        name: { fa: "شاتون", en: "Connecting Rod" },
        slugBase: "connecting-rod",
        weightGram: 600,
        dimensions: { lengthMm: 180, widthMm: 40, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 1_900_000,
        priceMaxRial: 3_800_000,
        oemPrefix: "12100",
      },
      {
        name: { fa: "پیستون کامل", en: "Piston Assembly" },
        slugBase: "piston-assembly",
        weightGram: 500,
        dimensions: { lengthMm: 90, widthMm: 90, heightMm: 90 },
        warrantyMonths: 6,
        priceMinRial: 1_600_000,
        priceMaxRial: 3_200_000,
        oemPrefix: "12010",
      },
    ],
  },
  {
    categorySlug: "transmission",
    templates: [
      {
        name: { fa: "دیسک کلاچ", en: "Clutch Disc" },
        slugBase: "clutch-disc",
        weightGram: 2200,
        dimensions: { lengthMm: 220, widthMm: 220, heightMm: 30 },
        warrantyMonths: 12,
        priceMinRial: 2_000_000,
        priceMaxRial: 4_000_000,
        oemPrefix: "30100",
      },
      {
        name: { fa: "صفحه کلاچ", en: "Clutch Pressure Plate" },
        slugBase: "clutch-pressure-plate",
        weightGram: 3500,
        dimensions: { lengthMm: 230, widthMm: 230, heightMm: 40 },
        warrantyMonths: 12,
        priceMinRial: 2_500_000,
        priceMaxRial: 4_500_000,
        oemPrefix: "31210",
      },
      {
        name: { fa: "بلبرینگ کلاچ", en: "Clutch Release Bearing" },
        slugBase: "clutch-release-bearing",
        weightGram: 300,
        dimensions: { lengthMm: 60, widthMm: 60, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 700_000,
        priceMaxRial: 1_500_000,
        oemPrefix: "31230",
      },
      {
        name: { fa: "سیم کلاچ", en: "Clutch Cable" },
        slugBase: "clutch-cable",
        weightGram: 400,
        dimensions: { lengthMm: 900, widthMm: 15, heightMm: 15 },
        warrantyMonths: 6,
        priceMinRial: 500_000,
        priceMaxRial: 1_100_000,
        oemPrefix: "23710",
      },
      {
        name: { fa: "دسته دنده", en: "Gear Shift Lever" },
        slugBase: "gear-shift-lever",
        weightGram: 600,
        dimensions: { lengthMm: 300, widthMm: 80, heightMm: 80 },
        warrantyMonths: 6,
        priceMinRial: 900_000,
        priceMaxRial: 1_800_000,
        oemPrefix: "25550",
      },
      {
        name: { fa: "گاردان کامل", en: "Complete Driveshaft" },
        slugBase: "complete-driveshaft",
        weightGram: 4500,
        dimensions: { lengthMm: 700, widthMm: 100, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 3_500_000,
        priceMaxRial: 7_000_000,
        oemPrefix: "43410",
      },
      {
        name: { fa: "توپی چرخ جلو", en: "Front Wheel Hub" },
        slugBase: "front-wheel-hub",
        weightGram: 1800,
        dimensions: { lengthMm: 150, widthMm: 150, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_600_000,
        oemPrefix: "43502",
      },
      {
        name: { fa: "کاسه‌نمد گیربکس", en: "Gearbox Oil Seal" },
        slugBase: "gearbox-oil-seal",
        weightGram: 80,
        dimensions: { lengthMm: 60, widthMm: 60, heightMm: 10 },
        warrantyMonths: 6,
        priceMinRial: 250_000,
        priceMaxRial: 550_000,
        oemPrefix: "90311",
      },
    ],
  },
  {
    categorySlug: "suspension-steering",
    templates: [
      {
        name: { fa: "کمک فنر جلو", en: "Front Shock Absorber" },
        slugBase: "front-shock-absorber",
        weightGram: 2500,
        dimensions: { lengthMm: 450, widthMm: 100, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_800_000,
        oemPrefix: "48510",
      },
      {
        name: { fa: "کمک فنر عقب", en: "Rear Shock Absorber" },
        slugBase: "rear-shock-absorber",
        weightGram: 2200,
        dimensions: { lengthMm: 400, widthMm: 100, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_600_000,
        priceMaxRial: 3_400_000,
        oemPrefix: "48530",
      },
      {
        name: { fa: "فنر لول جلو", en: "Front Coil Spring" },
        slugBase: "front-coil-spring",
        weightGram: 1800,
        dimensions: { lengthMm: 350, widthMm: 130, heightMm: 130 },
        warrantyMonths: 12,
        priceMinRial: 1_400_000,
        priceMaxRial: 2_800_000,
        oemPrefix: "48131",
      },
      {
        name: { fa: "سیبک فرمان", en: "Tie Rod End" },
        slugBase: "tie-rod-end",
        weightGram: 350,
        dimensions: { lengthMm: 150, widthMm: 50, heightMm: 50 },
        warrantyMonths: 6,
        priceMinRial: 500_000,
        priceMaxRial: 1_100_000,
        oemPrefix: "45046",
      },
      {
        name: { fa: "طبق جلو", en: "Front Control Arm" },
        slugBase: "front-control-arm",
        weightGram: 2800,
        dimensions: { lengthMm: 400, widthMm: 200, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_900_000,
        priceMaxRial: 3_900_000,
        oemPrefix: "48068",
      },
      {
        name: { fa: "جعبه فرمان", en: "Steering Rack" },
        slugBase: "steering-rack",
        weightGram: 5500,
        dimensions: { lengthMm: 700, widthMm: 150, heightMm: 150 },
        warrantyMonths: 12,
        priceMinRial: 4_500_000,
        priceMaxRial: 9_000_000,
        oemPrefix: "44250",
      },
      {
        name: { fa: "بوش طبق", en: "Control Arm Bushing" },
        slugBase: "control-arm-bushing",
        weightGram: 150,
        dimensions: { lengthMm: 60, widthMm: 60, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 300_000,
        priceMaxRial: 650_000,
        oemPrefix: "48655",
      },
      {
        name: { fa: "میل موجگیر", en: "Stabilizer Link" },
        slugBase: "stabilizer-link",
        weightGram: 300,
        dimensions: { lengthMm: 200, widthMm: 40, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 400_000,
        priceMaxRial: 900_000,
        oemPrefix: "48820",
      },
    ],
  },
  {
    categorySlug: "brakes",
    templates: [
      {
        name: { fa: "لنت ترمز جلو", en: "Front Brake Pad" },
        slugBase: "front-brake-pad",
        weightGram: 900,
        dimensions: { lengthMm: 150, widthMm: 100, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 700_000,
        priceMaxRial: 1_800_000,
        oemPrefix: "04465",
      },
      {
        name: { fa: "لنت ترمز عقب", en: "Rear Brake Pad" },
        slugBase: "rear-brake-pad",
        weightGram: 800,
        dimensions: { lengthMm: 140, widthMm: 90, heightMm: 35 },
        warrantyMonths: 6,
        priceMinRial: 600_000,
        priceMaxRial: 1_500_000,
        oemPrefix: "04466",
      },
      {
        name: { fa: "دیسک ترمز جلو", en: "Front Brake Disc" },
        slugBase: "front-brake-disc",
        weightGram: 5500,
        dimensions: { lengthMm: 280, widthMm: 280, heightMm: 25 },
        warrantyMonths: 12,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_200_000,
        oemPrefix: "43512",
      },
      {
        name: { fa: "دیسک ترمز عقب", en: "Rear Brake Disc" },
        slugBase: "rear-brake-disc",
        weightGram: 4800,
        dimensions: { lengthMm: 260, widthMm: 260, heightMm: 20 },
        warrantyMonths: 12,
        priceMinRial: 1_300_000,
        priceMaxRial: 2_900_000,
        oemPrefix: "42431",
      },
      {
        name: { fa: "کاسه ترمز عقب", en: "Rear Brake Drum" },
        slugBase: "rear-brake-drum",
        weightGram: 6000,
        dimensions: { lengthMm: 250, widthMm: 250, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_400_000,
        priceMaxRial: 2_700_000,
        oemPrefix: "42431",
      },
      {
        name: { fa: "سیلندر چرخ ترمز", en: "Wheel Brake Cylinder" },
        slugBase: "wheel-brake-cylinder",
        weightGram: 400,
        dimensions: { lengthMm: 80, widthMm: 60, heightMm: 60 },
        warrantyMonths: 6,
        priceMinRial: 500_000,
        priceMaxRial: 1_100_000,
        oemPrefix: "47550",
      },
      {
        name: { fa: "شیلنگ ترمز", en: "Brake Hose" },
        slugBase: "brake-hose",
        weightGram: 150,
        dimensions: { lengthMm: 400, widthMm: 15, heightMm: 15 },
        warrantyMonths: 6,
        priceMinRial: 250_000,
        priceMaxRial: 600_000,
        oemPrefix: "90947",
      },
      {
        name: { fa: "سیم ترمز دستی", en: "Handbrake Cable" },
        slugBase: "handbrake-cable",
        weightGram: 500,
        dimensions: { lengthMm: 1200, widthMm: 20, heightMm: 20 },
        warrantyMonths: 6,
        priceMinRial: 450_000,
        priceMaxRial: 950_000,
        oemPrefix: "46420",
      },
    ],
  },
  {
    categorySlug: "electrical",
    templates: [
      {
        name: { fa: "باتری ۶۰ آمپر", en: "60Ah Battery" },
        slugBase: "battery-60ah",
        weightGram: 15000,
        dimensions: { lengthMm: 240, widthMm: 175, heightMm: 190 },
        warrantyMonths: 18,
        priceMinRial: 3_500_000,
        priceMaxRial: 6_500_000,
        oemPrefix: "28800",
      },
      {
        name: { fa: "دینام", en: "Alternator" },
        slugBase: "alternator",
        weightGram: 4500,
        dimensions: { lengthMm: 180, widthMm: 150, heightMm: 150 },
        warrantyMonths: 12,
        priceMinRial: 4_000_000,
        priceMaxRial: 8_500_000,
        oemPrefix: "27060",
      },
      {
        name: { fa: "استارت", en: "Starter Motor" },
        slugBase: "starter-motor",
        weightGram: 3800,
        dimensions: { lengthMm: 200, widthMm: 120, heightMm: 120 },
        warrantyMonths: 12,
        priceMinRial: 3_800_000,
        priceMaxRial: 7_800_000,
        oemPrefix: "28100",
      },
      {
        name: { fa: "شمع موتور", en: "Spark Plug" },
        slugBase: "spark-plug",
        weightGram: 60,
        dimensions: { lengthMm: 70, widthMm: 20, heightMm: 20 },
        warrantyMonths: 6,
        priceMinRial: 180_000,
        priceMaxRial: 450_000,
        oemPrefix: "90919",
      },
      {
        name: { fa: "کویل جرقه", en: "Ignition Coil" },
        slugBase: "ignition-coil",
        weightGram: 300,
        dimensions: { lengthMm: 100, widthMm: 60, heightMm: 60 },
        warrantyMonths: 12,
        priceMinRial: 900_000,
        priceMaxRial: 2_000_000,
        oemPrefix: "90919",
      },
      {
        name: { fa: "چراغ جلو", en: "Headlight Assembly" },
        slugBase: "headlight-assembly",
        weightGram: 1500,
        dimensions: { lengthMm: 400, widthMm: 300, heightMm: 200 },
        warrantyMonths: 12,
        priceMinRial: 2_500_000,
        priceMaxRial: 5_500_000,
        oemPrefix: "81110",
      },
      {
        name: { fa: "چراغ عقب", en: "Taillight Assembly" },
        slugBase: "taillight-assembly",
        weightGram: 900,
        dimensions: { lengthMm: 300, widthMm: 200, heightMm: 150 },
        warrantyMonths: 12,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_200_000,
        oemPrefix: "81550",
      },
      {
        name: { fa: "سنسور ABS", en: "ABS Wheel Speed Sensor" },
        slugBase: "abs-wheel-speed-sensor",
        weightGram: 150,
        dimensions: { lengthMm: 100, widthMm: 30, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 700_000,
        priceMaxRial: 1_600_000,
        oemPrefix: "89543",
      },
    ],
  },
  {
    categorySlug: "body-exterior",
    templates: [
      {
        name: { fa: "سپر جلو", en: "Front Bumper" },
        slugBase: "front-bumper",
        weightGram: 6000,
        dimensions: { lengthMm: 1400, widthMm: 500, heightMm: 400 },
        warrantyMonths: 6,
        priceMinRial: 2_500_000,
        priceMaxRial: 5_500_000,
        oemPrefix: "52119",
      },
      {
        name: { fa: "سپر عقب", en: "Rear Bumper" },
        slugBase: "rear-bumper",
        weightGram: 5800,
        dimensions: { lengthMm: 1400, widthMm: 500, heightMm: 400 },
        warrantyMonths: 6,
        priceMinRial: 2_300_000,
        priceMaxRial: 5_200_000,
        oemPrefix: "52159",
      },
      {
        name: { fa: "آینه بغل برقی", en: "Power Side Mirror" },
        slugBase: "power-side-mirror",
        weightGram: 700,
        dimensions: { lengthMm: 200, widthMm: 150, heightMm: 150 },
        warrantyMonths: 6,
        priceMinRial: 1_200_000,
        priceMaxRial: 2_800_000,
        oemPrefix: "87910",
      },
      {
        name: { fa: "درب موتور", en: "Hood / Bonnet" },
        slugBase: "hood-bonnet",
        weightGram: 12000,
        dimensions: { lengthMm: 1300, widthMm: 1100, heightMm: 150 },
        warrantyMonths: 6,
        priceMinRial: 3_500_000,
        priceMaxRial: 7_500_000,
        oemPrefix: "53301",
      },
      {
        name: { fa: "گلگیر جلو", en: "Front Fender" },
        slugBase: "front-fender",
        weightGram: 3500,
        dimensions: { lengthMm: 900, widthMm: 500, heightMm: 100 },
        warrantyMonths: 6,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_800_000,
        oemPrefix: "53801",
      },
      {
        name: { fa: "نوار درب", en: "Door Weatherstrip" },
        slugBase: "door-weatherstrip",
        weightGram: 400,
        dimensions: { lengthMm: 1200, widthMm: 30, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 350_000,
        priceMaxRial: 750_000,
        oemPrefix: "67862",
      },
      {
        name: { fa: "دستگیره درب", en: "Door Handle" },
        slugBase: "door-handle",
        weightGram: 250,
        dimensions: { lengthMm: 200, widthMm: 50, heightMm: 50 },
        warrantyMonths: 6,
        priceMinRial: 400_000,
        priceMaxRial: 900_000,
        oemPrefix: "69210",
      },
      {
        name: { fa: "شیشه بغل جلو", en: "Front Door Glass" },
        slugBase: "front-door-glass",
        weightGram: 3000,
        dimensions: { lengthMm: 800, widthMm: 500, heightMm: 10 },
        warrantyMonths: 6,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_300_000,
        oemPrefix: "68101",
      },
    ],
  },
  {
    categorySlug: "cooling-ac",
    templates: [
      {
        name: { fa: "رادیاتور آب", en: "Water Radiator" },
        slugBase: "water-radiator",
        weightGram: 3500,
        dimensions: { lengthMm: 600, widthMm: 400, heightMm: 50 },
        warrantyMonths: 12,
        priceMinRial: 2_500_000,
        priceMaxRial: 5_500_000,
        oemPrefix: "16400",
      },
      {
        name: { fa: "کندانسور کولر", en: "AC Condenser" },
        slugBase: "ac-condenser",
        weightGram: 2500,
        dimensions: { lengthMm: 600, widthMm: 400, heightMm: 30 },
        warrantyMonths: 12,
        priceMinRial: 2_200_000,
        priceMaxRial: 4_800_000,
        oemPrefix: "88460",
      },
      {
        name: { fa: "کمپرسور کولر", en: "AC Compressor" },
        slugBase: "ac-compressor",
        weightGram: 5500,
        dimensions: { lengthMm: 250, widthMm: 180, heightMm: 180 },
        warrantyMonths: 12,
        priceMinRial: 5_500_000,
        priceMaxRial: 11_000_000,
        oemPrefix: "88310",
      },
      {
        name: { fa: "واترپمپ", en: "Water Pump" },
        slugBase: "water-pump",
        weightGram: 1800,
        dimensions: { lengthMm: 150, widthMm: 150, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_200_000,
        oemPrefix: "16100",
      },
      {
        name: { fa: "ترموستات", en: "Thermostat" },
        slugBase: "thermostat",
        weightGram: 200,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 60 },
        warrantyMonths: 6,
        priceMinRial: 400_000,
        priceMaxRial: 900_000,
        oemPrefix: "90916",
      },
      {
        name: { fa: "فن رادیاتور", en: "Radiator Cooling Fan" },
        slugBase: "radiator-cooling-fan",
        weightGram: 1200,
        dimensions: { lengthMm: 400, widthMm: 400, heightMm: 100 },
        warrantyMonths: 12,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_800_000,
        oemPrefix: "16711",
      },
      {
        name: { fa: "شیلنگ رادیاتور", en: "Radiator Hose" },
        slugBase: "radiator-hose",
        weightGram: 250,
        dimensions: { lengthMm: 400, widthMm: 40, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 300_000,
        priceMaxRial: 700_000,
        oemPrefix: "16571",
      },
      {
        name: { fa: "فیلتر درایر کولر", en: "AC Receiver Drier" },
        slugBase: "ac-receiver-drier",
        weightGram: 400,
        dimensions: { lengthMm: 150, widthMm: 60, heightMm: 60 },
        warrantyMonths: 6,
        priceMinRial: 600_000,
        priceMaxRial: 1_300_000,
        oemPrefix: "88470",
      },
    ],
  },
  {
    categorySlug: "exhaust",
    templates: [
      {
        name: { fa: "منیفولد اگزوز", en: "Exhaust Manifold" },
        slugBase: "exhaust-manifold",
        weightGram: 4500,
        dimensions: { lengthMm: 400, widthMm: 250, heightMm: 200 },
        warrantyMonths: 12,
        priceMinRial: 2_800_000,
        priceMaxRial: 5_800_000,
        oemPrefix: "17140",
      },
      {
        name: { fa: "لوله اگزوز میانی", en: "Mid Exhaust Pipe" },
        slugBase: "mid-exhaust-pipe",
        weightGram: 3200,
        dimensions: { lengthMm: 900, widthMm: 100, heightMm: 100 },
        warrantyMonths: 6,
        priceMinRial: 1_200_000,
        priceMaxRial: 2_600_000,
        oemPrefix: "17410",
      },
      {
        name: { fa: "صداخفه‌کن عقب", en: "Rear Muffler" },
        slugBase: "rear-muffler",
        weightGram: 5500,
        dimensions: { lengthMm: 600, widthMm: 200, heightMm: 200 },
        warrantyMonths: 12,
        priceMinRial: 2_200_000,
        priceMaxRial: 4_500_000,
        oemPrefix: "17650",
      },
      {
        name: { fa: "مبدل کاتالیزوری", en: "Catalytic Converter" },
        slugBase: "catalytic-converter",
        weightGram: 4800,
        dimensions: { lengthMm: 350, widthMm: 200, heightMm: 200 },
        warrantyMonths: 12,
        priceMinRial: 6_500_000,
        priceMaxRial: 13_000_000,
        oemPrefix: "17150",
      },
      {
        name: { fa: "واشر اگزوز", en: "Exhaust Gasket" },
        slugBase: "exhaust-gasket",
        weightGram: 80,
        dimensions: { lengthMm: 100, widthMm: 100, heightMm: 5 },
        warrantyMonths: 6,
        priceMinRial: 150_000,
        priceMaxRial: 350_000,
        oemPrefix: "17173",
      },
      {
        name: { fa: "بست اگزوز", en: "Exhaust Clamp" },
        slugBase: "exhaust-clamp",
        weightGram: 200,
        dimensions: { lengthMm: 100, widthMm: 80, heightMm: 40 },
        warrantyMonths: 6,
        priceMinRial: 120_000,
        priceMaxRial: 280_000,
        oemPrefix: "90460",
      },
      {
        name: { fa: "سنسور اکسیژن", en: "Oxygen Sensor" },
        slugBase: "oxygen-sensor",
        weightGram: 180,
        dimensions: { lengthMm: 120, widthMm: 30, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 1_200_000,
        priceMaxRial: 2_600_000,
        oemPrefix: "89465",
      },
      {
        name: { fa: "حلقه نگهدارنده اگزوز", en: "Exhaust Hanger Mount" },
        slugBase: "exhaust-hanger-mount",
        weightGram: 150,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 60 },
        warrantyMonths: 6,
        priceMinRial: 180_000,
        priceMaxRial: 400_000,
        oemPrefix: "17565",
      },
    ],
  },
  {
    categorySlug: "interior",
    templates: [
      {
        name: { fa: "صندلی راننده", en: "Driver Seat" },
        slugBase: "driver-seat",
        weightGram: 12000,
        dimensions: { lengthMm: 600, widthMm: 550, heightMm: 900 },
        warrantyMonths: 12,
        priceMinRial: 6_500_000,
        priceMaxRial: 14_000_000,
        oemPrefix: "71410",
      },
      {
        name: { fa: "روکش صندلی", en: "Seat Cover Set" },
        slugBase: "seat-cover-set",
        weightGram: 3500,
        dimensions: { lengthMm: 600, widthMm: 500, heightMm: 100 },
        warrantyMonths: 6,
        priceMinRial: 2_500_000,
        priceMaxRial: 5_500_000,
        oemPrefix: "71072",
      },
      {
        name: { fa: "کیلومترشمار", en: "Instrument Cluster" },
        slugBase: "instrument-cluster",
        weightGram: 800,
        dimensions: { lengthMm: 300, widthMm: 150, heightMm: 100 },
        warrantyMonths: 6,
        priceMinRial: 3_500_000,
        priceMaxRial: 7_500_000,
        oemPrefix: "83800",
      },
      {
        name: { fa: "پدال گاز", en: "Accelerator Pedal" },
        slugBase: "accelerator-pedal",
        weightGram: 400,
        dimensions: { lengthMm: 150, widthMm: 100, heightMm: 50 },
        warrantyMonths: 6,
        priceMinRial: 900_000,
        priceMaxRial: 2_000_000,
        oemPrefix: "78120",
      },
      {
        name: { fa: "دسته راهنما", en: "Turn Signal Stalk" },
        slugBase: "turn-signal-stalk",
        weightGram: 250,
        dimensions: { lengthMm: 200, widthMm: 60, heightMm: 60 },
        warrantyMonths: 6,
        priceMinRial: 700_000,
        priceMaxRial: 1_500_000,
        oemPrefix: "84310",
      },
      {
        name: { fa: "موتور بخاری", en: "Heater Blower Motor" },
        slugBase: "heater-blower-motor",
        weightGram: 900,
        dimensions: { lengthMm: 150, widthMm: 150, heightMm: 150 },
        warrantyMonths: 12,
        priceMinRial: 1_800_000,
        priceMaxRial: 3_800_000,
        oemPrefix: "87103",
      },
      {
        name: { fa: "آفتابگیر", en: "Sun Visor" },
        slugBase: "sun-visor",
        weightGram: 300,
        dimensions: { lengthMm: 300, widthMm: 150, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 350_000,
        priceMaxRial: 750_000,
        oemPrefix: "74320",
      },
      {
        name: { fa: "کف‌پوش سلفونی", en: "Floor Mat Set" },
        slugBase: "floor-mat-set",
        weightGram: 2500,
        dimensions: { lengthMm: 1000, widthMm: 500, heightMm: 30 },
        warrantyMonths: 6,
        priceMinRial: 900_000,
        priceMaxRial: 2_000_000,
        oemPrefix: "58259",
      },
    ],
  },
  {
    categorySlug: "filters-fluids",
    templates: [
      {
        name: { fa: "فیلتر روغن", en: "Oil Filter" },
        slugBase: "oil-filter",
        weightGram: 250,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 100 },
        warrantyMonths: 3,
        priceMinRial: 250_000,
        priceMaxRial: 550_000,
        oemPrefix: "15400",
      },
      {
        name: { fa: "فیلتر هوا", en: "Air Filter" },
        slugBase: "air-filter",
        weightGram: 300,
        dimensions: { lengthMm: 250, widthMm: 200, heightMm: 50 },
        warrantyMonths: 3,
        priceMinRial: 280_000,
        priceMaxRial: 600_000,
        oemPrefix: "17801",
      },
      {
        name: { fa: "فیلتر بنزین", en: "Fuel Filter" },
        slugBase: "fuel-filter",
        weightGram: 200,
        dimensions: { lengthMm: 100, widthMm: 60, heightMm: 60 },
        warrantyMonths: 3,
        priceMinRial: 300_000,
        priceMaxRial: 650_000,
        oemPrefix: "23300",
      },
      {
        name: { fa: "فیلتر کابین", en: "Cabin Air Filter" },
        slugBase: "cabin-air-filter",
        weightGram: 180,
        dimensions: { lengthMm: 250, widthMm: 180, heightMm: 30 },
        warrantyMonths: 3,
        priceMinRial: 350_000,
        priceMaxRial: 750_000,
        oemPrefix: "87139",
      },
      {
        name: { fa: "روغن موتور ۴ لیتری", en: "4L Engine Oil" },
        slugBase: "engine-oil-4l",
        weightGram: 3600,
        dimensions: { lengthMm: 200, widthMm: 150, heightMm: 250 },
        warrantyMonths: 0,
        priceMinRial: 1_500_000,
        priceMaxRial: 3_500_000,
        oemPrefix: "08880",
      },
      {
        name: { fa: "روغن ترمز", en: "Brake Fluid" },
        slugBase: "brake-fluid",
        weightGram: 500,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 150 },
        warrantyMonths: 0,
        priceMinRial: 250_000,
        priceMaxRial: 550_000,
        oemPrefix: "08823",
      },
      {
        name: { fa: "ضدیخ رادیاتور", en: "Radiator Antifreeze" },
        slugBase: "radiator-antifreeze",
        weightGram: 4000,
        dimensions: { lengthMm: 150, widthMm: 150, heightMm: 300 },
        warrantyMonths: 0,
        priceMinRial: 600_000,
        priceMaxRial: 1_300_000,
        oemPrefix: "08889",
      },
      {
        name: { fa: "گریس یاتاقان", en: "Bearing Grease" },
        slugBase: "bearing-grease",
        weightGram: 500,
        dimensions: { lengthMm: 80, widthMm: 80, heightMm: 100 },
        warrantyMonths: 0,
        priceMinRial: 200_000,
        priceMaxRial: 450_000,
        oemPrefix: "08887",
      },
    ],
  },
];
